[build-system]
requires = ["scikit-build-core", "pybind11", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "fastvoxel"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = ["numpy"]
